services:
  # =========================
  # Backend Django
  # =========================
  - type: web
    name: super-dkf-backend
    env: python
    region: frankfurt
    plan: free
    rootDir: my_store
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn my_store.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: super-dkf-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://super-dkf-frontend.onrender.com
      - key: CREATE_SUPERUSER
        value: "True"
      - key: SUPERUSER_USERNAME
        value: "admin"
      - key: SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: SUPERUSER_PASSWORD
        generateValue: true
    healthCheckPath: /

  # =========================
  # Frontend React
  # =========================
  - type: web
    name: super-dkf-frontend
    env: node
    region: frankfurt
    plan: free
    rootDir: react-app
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: VITE_API_BASE_URL
        fromService:
          name: super-dkf-backend
          type: web
          property: host
          format: https://${host}/api

databases:
  # =========================
  # PostgreSQL (SEULEMENT ICI)
  # =========================
  - name: super-dkf-db
    region: frankfurt
    plan: free
